# CPI and Unemplyoment Rate

```{r}
library(tidyverse)
library(eurostat)
```


## Annual CPI

from [eurostat prc_hicp_aind](https://ec.europa.eu/eurostat/databrowser/view/prc_hicp_aind/default/table?lang=en)

```{r}
df_cpi_raw <- get_eurostat(
  "prc_hicp_aind", 
  filters=list(
    coicop = "CP00", # all items
    unit = "INX_A_AVG", # index, annual average (2015=100 at this point in time)
    sinceTimePeriod=2010
  ),
)

df_cpi_raw <- label_eurostat(df_cpi_raw, code=c("coicop","unit"), countrycode=c("iso3c") )
```

```{r}
df_cpi <- df_cpi_raw %>%
  filter(
    str_length(geo) == 3, # only countries, no aggregates
    geo != "EEA"
    ) %>% 
  mutate(
    country_name = countrycode(geo, origin="iso3c", destination="country.name"),
    FINAL_CODE = paste0(geo, "_", "HIC", "_ESTAT"),
    year = year(time)
  ) %>%
  select(coicop, country_name, unit, FINAL_CODE, year, values) %>%
  pivot_wider(names_from = year, values_from = values) 

df_cpi
```

```{r}
write_csv(df_cpi, "../../data/eurostat_processed/CPI_A.csv")
```

## Quarterly CPI

CONTINUE
```

