# Comparing the Datasets

Monthly Analysis

```{r}
library(tidyverse)
library(visdat)
```

```{r}
df_old <- read_csv("../../examples/imf/adv_monthly.csv")
df_new <- read_csv("../../data/imf_processed/adv_monthly.csv")
```
## ENDA_XDC_USD_RATE

```{r}
df_old_ENDA <-  df_old %>%
  filter(
    `Indicator Code` == "ENDA_XDC_USD_RATE",
    `Attribute` == "Value",
    `Country Code` != 171 # Remove Andorra (not in new data) 
    
    ) %>%
  select(-`Base Year`) %>%
  mutate(across(starts_with("19"), ~ round(as.numeric(.x), 3))) %>%
  mutate(across(starts_with("20"), ~ round(as.numeric(.x), 3))) %>%
  arrange(`Country Code`)
  

df_new_ENDA <-  df_new %>%
  filter(
    `Indicator Code` == "ENDA_XDC_USD_RATE",
    `Attribute` == "Value",
    `Country Code` != 110 # Remove Advanced Economies (not in old data)
    ) %>%
  mutate(across(starts_with("19"), ~ round(as.numeric(.x), 3))) %>%
  mutate(across(starts_with("20"), ~ round(as.numeric(.x), 3))) %>%
  select(-c("2025M8", "2025M9", "2025M10", "2025M11", "2025M12", "2026M1")) %>% # New columns not in old data
  arrange(`Country Code`)
```

compare Country Codes
```{r}
setdiff(df_old_ENDA$`Country Code`, df_new_ENDA$`Country Code`) #171 = Andorra 
setdiff(df_new_ENDA$`Country Code`, df_old_ENDA$`Country Code`) #110 = Advanced Economies 
```


```{r}
vis_compare(
  df_old_ENDA,
  df_new_ENDA
  )
```
=> exactly the same, except for some missing values for Eurozone in new (its in the country data still)

## FPOLM_PA

```{r}
df_old_FPOLM <-  df_old %>%
  filter(
    `Indicator Code` == "FPOLM_PA",
    `Attribute` == "Value",
    `Country Code` != 171 # Remove Andorra (not in new data) 
  ) %>%
  select(-`Base Year`) %>%
  mutate(across(starts_with("19"), ~ round(as.numeric(.x), 3))) %>%
  mutate(across(starts_with("20"), ~ round(as.numeric(.x), 3))) %>%
  arrange(`Country Code`) %>%
  #filter for all countries that have data at least once
  filter(if_any(starts_with("19"), ~ !is.na(.x)) | if_any(starts_with("20"), ~ !is.na(.x)))

df_new_FPOLM <-  df_new %>%
  filter(
    `Indicator Code` == "FPOLM_PA",
    `Attribute` == "Value",
    `Country Code` != 110 # Remove Advanced Economies (not in old data)
  ) %>%
  mutate(across(starts_with("19"), ~ round(as.numeric(.x), 3))) %>%
  mutate(across(starts_with("20"), ~ round(as.numeric(.x), 3))) %>%
  select(-c("2025M8", "2025M9", "2025M10", "2025M11", "2025M12", "2026M1")) %>% # New columns not in old data
  arrange(`Country Code`) %>%
  #filter for all countries that have data at least once
  filter(if_any(starts_with("19"), ~ !is.na(.x)) | if_any(starts_with("20"), ~ !is.na(.x)))
```

```{r}
setdiff(df_old_FPOLM$`Country Code`, df_new_FPOLM$`Country Code`) 
setdiff(df_new_FPOLM$`Country Code`, df_old_FPOLM$`Country Code`) 
```

Countries in old: 112 (UK), 146 (CH), 163 (Euro), 576 (SGP)
Countries in new: 128 (DK), 144 (SE), 935 (CZ)

After filtering for common countries: exactly the same
```{r}
vis_compare(
  df_old_FPOLM %>% filter(`Country Code` %in% intersect(df_old_FPOLM$`Country Code`, df_new_FPOLM$`Country Code`)),
  df_new_FPOLM %>% filter(`Country Code` %in% intersect(df_old_FPOLM$`Country Code`, df_new_FPOLM$`Country Code`))
  )
```

